package com.example.itantra.security

import android.content.Context
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Owns the AES-256 session key lifecycle for iTantra: Setu.
 *
 * The problem this solves
 * -----------------------
 * `CryptoEngine` correctly refuses to embed a key, so it derived a random key
 * per process. Two phones therefore held different keys and every packet failed
 * authentication on the receiver - the encrypted pipeline could not be
 * demonstrated across devices at all.
 *
 * The prototype answer is OUT-OF-BAND pairing:
 *
 *   Phone A                     Phone B
 *   ------                      -------
 *   generate key
 *   show SETU-XXXX-... code  --> operator reads/scans it
 *                                adopt code
 *   seal in Keystore            seal in Keystore
 *
 * Both devices now hold identical key material, persisted only as a
 * Keystore-sealed envelope (see [KeyEnvelope]).
 *
 * Honest scope statement
 * ----------------------
 * This is NOT authenticated key exchange. The pairing code is a bearer secret
 * transported by a human over a voice call or a camera. Anyone who obtains the
 * code can decrypt every packet. That is acceptable for a face-to-face
 * prototype demo and is labelled as such in the UI.
 *
 * The seam for real key exchange
 * ------------------------------
 * [adoptPairingCode] is the single entry point where key material enters the
 * system. Replacing it with an X25519/ECDH agreement (and [seal]/[open] storage
 * per participant) requires no change to [CryptoEngine], [SetuPacket],
 * [TransportManager] or any UI. No ECDH code is included here on purpose.
 */
class SessionKeyManager(context: Context) {

    /** Why the current session key is in the state it is. */
    enum class Source {
        /** No key has been provisioned yet; a random ephemeral key is in use. */
        EPHEMERAL,

        /** This device generated the key and is showing the pairing code. */
        GENERATED_HERE,

        /** This device adopted a pairing code from the peer device. */
        ADOPTED_FROM_PEER,

        /** A previously paired key was restored from the Keystore envelope. */
        RESTORED
    }

    data class KeyState(
        val source: Source = Source.EPHEMERAL,
        val fingerprint: String = "",
        val pairingCode: String? = null,
        val persisted: Boolean = false,
        val notice: String = "NOT PAIRED - each device holds a different random key, so packets will NOT decrypt across devices"
    ) {
        val isPaired: Boolean get() = source != Source.EPHEMERAL
    }

    private val prefs = context.applicationContext
        .getSharedPreferences(PREFS, Context.MODE_PRIVATE)

    private val _state = MutableStateFlow(KeyState())

    /** Observable key state for the UI. Never exposes key material. */
    val state: StateFlow<KeyState> = _state.asStateFlow()

    init {
        restore()
    }

    /**
     * Generates a new 256-bit key on THIS device and returns the pairing code
     * the peer must read. The generated key is also sealed locally so it
     * survives a restart.
     */
    fun generateAndShowCode(): PairingCodeResult {
        if (!KeyEnvelope.isAvailable()) {
            val reason = "Android Keystore unavailable - cannot persist a shared key securely"
            _state.value = KeyState(notice = reason)
            return PairingCodeResult.Failure(reason)
        }

        val key = CryptoEngine.generateSessionKey()
        val raw = key.encoded
        val code = PairingCode.encode(raw)
        val sealed = KeyEnvelope.seal(raw)

        if (sealed == null) {
            val reason = "Failed to seal session key in Android Keystore"
            _state.value = KeyState(notice = reason)
            return PairingCodeResult.Failure(reason)
        }

        CryptoEngine.setSessionKey(key)
        persist(sealed, PairingCode.fingerprint(raw), Source.GENERATED_HERE)
        _state.value = KeyState(
            source = Source.GENERATED_HERE,
            fingerprint = PairingCode.fingerprint(raw),
            pairingCode = code,
            persisted = true,
            notice = "Read this code to Phone B, then adopt it there"
        )
        return PairingCodeResult.Success(code, PairingCode.fingerprint(raw))
    }

    /**
     * Adopts a pairing code generated by the peer device and installs the
     * resulting key as the active session key.
     */
    fun adoptPairingCode(code: String): PairingCodeResult {
        val raw = PairingCode.decode(code)
        if (raw == null) {
            val reason = "Pairing code invalid - check for transcription errors"
            _state.value = _state.value.copy(notice = reason)
            return PairingCodeResult.Failure(reason)
        }

        if (!KeyEnvelope.isAvailable()) {
            val reason = "Android Keystore unavailable - cannot persist the shared key"
            // Still install for this process so a demo can proceed, but say so.
            CryptoEngine.setSessionKey(CryptoEngine.importKey(raw))
            _state.value = KeyState(
                source = Source.ADOPTED_FROM_PEER,
                fingerprint = PairingCode.fingerprint(raw),
                pairingCode = null,
                persisted = false,
                notice = "PAIRED FOR THIS SESSION ONLY - key will be lost on restart"
            )
            return PairingCodeResult.Failure(reason)
        }

        val sealed = KeyEnvelope.seal(raw)
        if (sealed == null) {
            val reason = "Failed to seal session key in Android Keystore"
            _state.value = _state.value.copy(notice = reason)
            return PairingCodeResult.Failure(reason)
        }

        CryptoEngine.setSessionKey(CryptoEngine.importKey(raw))
        persist(sealed, PairingCode.fingerprint(raw), Source.ADOPTED_FROM_PEER)
        _state.value = KeyState(
            source = Source.ADOPTED_FROM_PEER,
            fingerprint = PairingCode.fingerprint(raw),
            pairingCode = null,
            persisted = true,
            notice = "Paired with peer - both devices now share one AES-256 key"
        )
        return PairingCodeResult.Success(null, PairingCode.fingerprint(raw))
    }

    /** True when the fingerprint shown on both devices matches. */
    fun matchesPeerFingerprint(peerFingerprint: String): Boolean {
        val mine = _state.value.fingerprint
        return mine.isNotEmpty() && mine.equals(peerFingerprint.trim().uppercase(), ignoreCase = true)
    }

    /**
     * Forgets the paired key and destroys the Keystore wrapping key, returning
     * the device to a random ephemeral key.
     */
    fun forgetPairing() {
        prefs.edit().remove(KEY_SEALED).remove(KEY_FINGERPRINT).remove(KEY_SOURCE).apply()
        KeyEnvelope.destroy()
        _state.value = KeyState(
            notice = "Pairing cleared - re-pair before sending between devices"
        )
    }

    /**
     * Reloads a previously sealed key. Reports honestly (and resets to an
     * ephemeral key) when the envelope cannot be opened, which happens if the
     * Keystore key was invalidated by a lock-screen change or app data clear.
     */
    private fun restore() {
        val sealed = prefs.getString(KEY_SEALED, null)
        if (sealed.isNullOrBlank()) {
            _state.value = KeyState()
            return
        }

        val raw = KeyEnvelope.open(sealed)
        if (raw == null) {
            prefs.edit().remove(KEY_SEALED).remove(KEY_FINGERPRINT).remove(KEY_SOURCE).apply()
            _state.value = KeyState(
                notice = "Stored key could not be opened (Keystore invalidated) - re-pair required"
            )
            return
        }

        val storedFingerprint = prefs.getString(KEY_FINGERPRINT, "") ?: ""
        val fingerprint = PairingCode.fingerprint(raw)
        CryptoEngine.setSessionKey(CryptoEngine.importKey(raw))

        val source = try {
            Source.valueOf(prefs.getString(KEY_SOURCE, null) ?: Source.RESTORED.name)
        } catch (_: Exception) {
            Source.RESTORED
        }

        _state.value = KeyState(
            source = source,
            fingerprint = fingerprint,
            pairingCode = null,
            persisted = true,
            notice = if (storedFingerprint == fingerprint) {
                "Paired key restored from Android Keystore"
            } else {
                "Stored key restored (fingerprint changed - re-pair to be safe)"
            }
        )
    }

    private fun persist(sealed: String, fingerprint: String, source: Source) {
        prefs.edit()
            .putString(KEY_SEALED, sealed)
            .putString(KEY_FINGERPRINT, fingerprint)
            .putString(KEY_SOURCE, source.name)
            .apply()
    }

    sealed interface PairingCodeResult {
        data class Success(val pairingCode: String?, val fingerprint: String) : PairingCodeResult
        data class Failure(val reason: String) : PairingCodeResult
    }

    private companion object {
        const val PREFS = "itantra_setu_pairing"
        const val KEY_SEALED = "sealed_session_key"
        const val KEY_FINGERPRINT = "session_key_fingerprint"
        const val KEY_SOURCE = "session_key_source"
    }
}
